name: Image

on:
  push:
    branches:
      - "main"
      - "ci"

jobs:
  build-images:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up DockerBuildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          network: host
          push: true
          tags:
            ghcr.io/cardano-scaling/doom-matchmaking-bot,ghcr.io/doom-matchmaking-bot:${{
            github.sha }}
